steps:
  - name: "gcr.io/cloud-builders/docker"
    args: [
      "build",
      "-t",
      "gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA",
      ".",
      "--build-arg", "DISCORD_TOKEN=${_DISCORD_TOKEN}",
      "--build-arg", "MINECRAFT_URI=${_MINECRAFT_URI}"
    ]
images:
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA'
