name: Build and push image to GCR, deploy if on master
on: [push]

env:
  PROJECT_ID: ${{ secrets.RUN_PROJECT }}
  PROJECT_NAME: block-bot
  GCE_INSTANCE: ${{ secrets.INSTANCE_NAME }}
  GCE_INSTANCE_ZONE: ${{ secrets.INSTANCE_ZONE }}
  MINECRAFT_URI: ${{ secrets.MINECRAFT_URI }}
  DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
jobs:
  build-and-push:
    name: build, test, and push
    runs-on: ubuntu-latest
    steps:
      - name: check out the repo
        uses: actions/checkout@v2
      - name: set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylama pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: lint with pylama
        run: |
          # stop the build if there are Python syntax errors or undefined names
          pylama -o pylama.ini
      - name: test with pytest
        run: |
          pytest
      - name: setup gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.RUN_SA_KEY }}
          project_id: ${{ secrets.RUN_PROJECT }}
      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - name: authorize with GCR
        run: |-
          gcloud --quiet auth configure-docker
      # Build the Docker image
      - name: container build
        run: |-
          docker build --tag "gcr.io/$PROJECT_ID/$PROJECT_NAME:$GITHUB_SHA" \
          --build-arg DISCORD_TOKEN=${DISCORD_TOKEN} \
          --build-arg MINECRAFT_URI='${MINECRAFT_URI}' \
          .
      # Push the Docker image to Google Container Registry
      - name: publish to GCR
        run: |-
          docker push "gcr.io/$PROJECT_ID/$PROJECT_NAME:$GITHUB_SHA"
  deploy:
    name: deploy master to production
    runs-on: ubuntu-latest
    needs: build-and-push
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - name: setup gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.RUN_SA_KEY }}
          project_id: ${{ secrets.RUN_PROJECT }}
      - name: deploy to GCE
        run: |-
          gcloud compute instances update-container "$GCE_INSTANCE" \
            --zone "$GCE_INSTANCE_ZONE" \
            --container-image "gcr.io/$PROJECT_ID/$PROJECT_NAME:$GITHUB_SHA"
